baseurl = "https://angusjellis.co.uk/"
title = "Angus Jellis"
author = "Angus Jellis"
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

enableEmoji = true
hasCJKLanguage = false

pygmentsstyle = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[params]
  sitename = "Angus Jellis"
  faviconfile = "images/favicon.png"
  highlightjs = true
  highlightjslanguages = ["r", "python", "stan"]
  uselatex = true
  progressively = false

# commentsrepo = "user/repo"

[taxonomies]
  category = "categories"
  long = "long"
  tag = "tags"
  short = "short"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.primary]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.primary]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.primary]]
    name = "Tech Stack"
    url = "/techstack/"
    weight = 3
[[menu.primary]]
    name = "Posts"
    url = "/posts/"
    weight = 4
[[menu.primary]]
    name = "CV"
    url = "/cv.pdf"
    weight = 4
[[menu.primary]]
    name = "GitHub"
    url = "https://github.com/angusjellis"
    weight = 5
[[menu.primary]]
    name = "Twitter"
    url = "https://twitter.com/angusjellis"
    weight = 6
