name: Python Flask CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Install dependencies
        run: |
          python -m venv env
          source env/bin/activate
          pip install -r requirements.txt
      - name: Run tests
        run: |
          source env/bin/activate
          pytest --cov=app tests/
      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: my-bucket
          AWS_REGION: eu-west-1
          SOURCE_DIR: "app/"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v17
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: my-application
          environment_name: my-environment
          version_label: ${{ github.sha }}
          region: us-east-1
          deployment_package: "app.zip"
          
  integration_test:
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - name: Install dependencies
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Download code from S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: my-bucket
          AWS_REGION: eu-west-1
          DEST_DIR: "app/"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Run integration tests
        run: |
          python -m venv env
          source env/bin/activate
          pip install -r requirements.txt
          pytest tests/integration/
          
  deploy_production:
    runs-on: ubuntu-latest
    needs: integration_test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download code from S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: my-bucket
          AWS_REGION: eu-west-1
          DEST_DIR: "app/"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Deploy to production
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: my-application
          environment_name: my-environment-production
          version_label: ${{ github.sha }}
          region: eu-west-1
          deployment_package: "app.zip"